#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --architectures amd64 \
    --debian-installer none \
    --archive-areas "main contrib non-free" \
    --apt-indices false \
    --bootappend-live "iomem=relaxed" \
    --bootappend-live-failsafe "iomem=relaxed" \
    --binary-image iso-hybrid \
    --memtest none \
    "${@}"
