#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --architectures amd64 \
    --debian-installer none \
    --archive-areas "main contrib non-free" \
    --apt-indices false \
    --bootappend-live "boot=live components iomem=relaxed intel_iommu=off amd_iommu=off" \
    --bootappend-live-failsafe "boot=live components iomem=relaxed intel_iommu=off amd_iommu=off" \
    --binary-image iso-hybrid \
    --memtest none \
    "${@}"
